version: "3.8"

services:
  missions-db:
    build: ./missions-db
    container_name: missions-db
    networks:
      - missions-network
    volumes:
      - missions-bdd-data:/var/lib/postgresq/data

  missions-back:
    build: https://github.com/2020-d05-java-devops/gestion-des-missions-back.git
    container_name: missions-back
    depends_on:
      - missions-db
    ports:
      - "8080:8080"
    networks:
      - missions-network

  missions-front:
    build: .
    container_name: missions-front
    depends_on:
      - missions-back
    ports:
      - "8081:8081"
    networks:
      - missions-network

networks:
  missions-network:

volumes:
  missions-bdd-data:
